/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ArrowDownOutlined: typeof import('@ant-design/icons')['ArrowDownOutlined']
  const ArrowUpOutlined: typeof import('@ant-design/icons')['ArrowUpOutlined']
  const Avatar: typeof import('antd')['Avatar']
  const Button: typeof import('antd')['Button']
  const CloseOutlined: typeof import('@ant-design/icons')['CloseOutlined']
  const DownOutlined: typeof import('@ant-design/icons')['DownOutlined']
  const Dropdown: typeof import('antd')['Dropdown']
  const Link: typeof import('react-router-dom')['Link']
  const NavLink: typeof import('react-router-dom')['NavLink']
  const Navigate: typeof import('react-router-dom')['Navigate']
  const Outlet: typeof import('react-router-dom')['Outlet']
  const Popconfirm: typeof import('antd')['Popconfirm']
  const Progress: typeof import('antd')['Progress']
  const Provider: typeof import('react-redux')['Provider']
  const Route: typeof import('react-router-dom')['Route']
  const Routes: typeof import('react-router-dom')['Routes']
  const Slider: typeof import('antd')['Slider']
  const Space: typeof import('antd')['Space']
  const Tooltip: typeof import('antd')['Tooltip']
  const UserOutlined: typeof import('@ant-design/icons')['UserOutlined']
  const WarningOutlined: typeof import('@ant-design/icons')['WarningOutlined']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const message: typeof import('antd')['message']
  const notification: typeof import('antd')['notification']
  const startTransition: typeof import('react')['startTransition']
  const styled: typeof import('styled-components')['styled']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useDispatch: typeof import('react-redux')['useDispatch']
  const useEffect: typeof import('react')['useEffect']
  const useHref: typeof import('react-router-dom')['useHref']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInRouterContext: typeof import('react-router-dom')['useInRouterContext']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useLinkClickHandler: typeof import('react-router-dom')['useLinkClickHandler']
  const useLocation: typeof import('react-router-dom')['useLocation']
  const useMemo: typeof import('react')['useMemo']
  const useNavigate: typeof import('react-router-dom')['useNavigate']
  const useNavigationType: typeof import('react-router-dom')['useNavigationType']
  const useOutlet: typeof import('react-router-dom')['useOutlet']
  const useOutletContext: typeof import('react-router-dom')['useOutletContext']
  const useParams: typeof import('react-router-dom')['useParams']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useResolvedPath: typeof import('react-router-dom')['useResolvedPath']
  const useRoutes: typeof import('react-router-dom')['useRoutes']
  const useSearchParams: typeof import('react-router-dom')['useSearchParams']
  const useSelector: typeof import('react-redux')['useSelector']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { RootState } from '@/stores'
  import('@/stores')
}
